# This file doesn't need to be changed. It's the same for everyone
# Note: the 'host' has to match the 'services' name int he github actions .yml file
host: db_service
database: swen344
user: swen344
password: whowatchesthewatchmen
port: 5432