name: Test Workflow

on: push 

jobs:
 test:
   runs-on: ubuntu-latest
   
   services:
    image: postgres
    env:
    - POSTGRES_USER: swen344
    - POSTGRES_PASSWORD: whowatchesthewatchmen
    - POSTGRES_DB: swen344
    ports:
    - 5432:5432
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
   
   steps:
   - uses: actions/checkout@v2
   - name: Set up Python 3.8.9
   - uses: actions/setup-python@v2
     with:
      python-version: 3.8.9

   - name: Install dependencies
     run: cd rest-1
     run: pip install -r requirements.txt
     run: python src/server.py &
     run: sleep 3
   - name: Run tests
     run: python -m unittest -v